### ISSUE TITLE
Cannot install a module without an index.js at root after require() has been called once

### ISSUE THREAD

**Issue by deepal** [deepal/baapan#28]
Steps to reproduce:

- Install `chance` first
- Install `underscore` second

`underscore` does not have an `index.js` at the module root. Instead, the entry point  is configured via `main` attribute in `package.json`

```
> require('chance')
Fetching and installing module 'chance' from npm...
Done!
[Function: Chance] { Chance: [Circular] }
> require('underscore')
Fetching and installing module 'underscore' from npm...
Done!
Uncaught:
Error: Cannot find module '/Users/deepal/.baapan/workspace_90531_1584193257750/node_modules/underscore'
Require stack:
- <repl>
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at Module._module.Module.require (/Users/deepal/Projects/baapan/src/baapan.js:131:34)
    at require (internal/modules/cjs/helpers.js:77:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '<repl>' ]
}
> 
```

This happens if the `require()` has been called once to install a module dynamically. Installation of the second module is successful, but it cannot be `require`d and throws `MODULE_NOT_FOUND` error.

**Comment by deepal** [comment]
This issue is being investigated. Until then a minor workaround is added in https://github.com/deepal/baapan/pull/31 and a compatibility warning is displayed as follows.

<img width="970" alt="Screenshot 2020-03-15 at 21 12 53" src="https://user-images.githubusercontent.com/1533286/76710746-ea321380-6701-11ea-8dc4-a7929448b998.png">
