### ISSUE TITLE
User friendly error message when the module installation fails

### ISSUE THREAD

**Issue by deepal** [deepal/baapan#8]
The following error is thrown during installing a module when the module is not found in NPM. This error message is vague and does not indicate the specific error. This needs to be improved.

```
Creating workspace...
Initializing workspace...
Workspace loaded!
> require('ERTGB23456789sdf_')
Fetching and installing module 'ERTGB23456789sdf_' from npm...
Thrown:
{ Error: Command failed: npm install --silent ERTGB23456789sdf_
    at require (internal/modules/cjs/helpers.js:25:18)
    at Module.installModule [as require] (/Users/djayasekara/MyProjects/baapan/index.js:203:7)
    at installModule (/Users/djayasekara/MyProjects/baapan/index.js:73:3)
    at execSync (child_process.js:666:13)
    at checkExecSyncError (child_process.js:629:11)
  status: 1,
  signal: null,
  output: [ null, <Buffer >, <Buffer > ],
  pid: 7825,
  stdout: <Buffer >,
  stderr: <Buffer > }
>  
```

**Comment by deepal** [comment]
This is addressed in https://github.com/deepal/baapan/pull/31
